### ISSUE TITLE
Wrong path to the file

### ISSUE THREAD

**Issue by boyarskiy** [numo-labs/aws-lambda-deploy#21]
When I run `npm run deploy` locally, I got the error:

![bug](https://cloud.githubusercontent.com/assets/2486360/13285132/9e098942-db01-11e5-83db-18b5f4ab9f93.jpg)

The path must be: `/home/user/numo/aws/lambda-promote/lib/schema/index.js`

**Comment by nelsonic** [comment]
Thanks for reporting this. I will add a regression test and fix for this shortly. :+1:
