### ISSUE TITLE
Add ES6 Support

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/aws-lambda-deploy#23]
As a trendy JS developer, 
I want to copy the ES6 code style I see on Medium, 
so that I can look cool to all my friends. 
<hr />
**tl;dr**
There is no *convincing* argument in favour of using ES6 features 
(e.g: `const`, `let`, `import bla from 'bla'`, `=>` ) in code that will be deployed to **Lambda** (which only supports ES5)

Sure, it might be *fewer characters* for the developer to type `=>` instead of `function`, but the resulting "*transpiled*" code is ***always bigger*** than if you just wrote ES5 in the first place because `babel` adds "*boilerplate*" code to your code... e.g:

```js
'use strict';

var _starwarsService = require('./lib/starwars-service');

var _starwarsService2 = _interopRequireDefault(_starwarsService);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

exports.handler = function (event, context) {
  _starwarsService2.default.quote(event.isHuman, function (err, message) {
    if (err) {
      return context.fail(JSON.stringify({
        statusCode: 500,
        message: err
      }));
    } else {
      return context.succeed({
        statusCode: 200,
        message: message
      });
    }
  });
};
```

The resulting "*transpiled*" code from ES6 to ES5 using `babel` is 5%-10% larger, meaning it takes more time/memory to execute the Lambda Function! Which means we spend more money on AWS and our *end-users* have to wait more time for their result. 

But, given that *fashion* dictates decisions more than *common sense*, we are forced to add ES6 support to this deployment tool.

Lets *ignore* the fact that Babel is *so buggy* that they have *disabled* "*issues*" on their GitHub Repo and instead created their own bug tracker: https://phabricator.babeljs.io/ which does not display the total number of bugs (*because there are* ***thousands***...!)

Ignore the fact that that the time you *think* you saved typing fewer characters in your ES6 code, you will spend waiting for transpilation and/or debugging the "*transpiled*" code...

Also ignore the fact *fact* that Babel has known security vulnerabilities in its devDependencies: [![devDependency Status](https://david-dm.org/babel/babel/dev-status.svg)](https://david-dm.org/babel/babel#info=devDependencies) which nobody is *responsible* for updating. 
And because of the "Monorepo" its *virtually impossible* to keep track of which dependencies have issues... [![Dependency Status](https://david-dm.org/babel/babel.svg)](https://david-dm.org/babel/babel)

**Comment by nelsonic** [comment]
Adding babel installs 200 Megabytes on your Machine...
![adding-babel-dependencies](https://cloud.githubusercontent.com/assets/194400/13321493/39fcfa30-dbc7-11e5-8b05-f046675f9cb6.png)

**Comment by s-voloshynenko** [comment]
What if AWS will add the ability to use *node.js >=4.x* versions, then it will be necessary to add additional option if transforming really needed. Maybe it should be extensible with plugins, a la `dpl-transpile` and so on.

**Comment by nelsonic** [comment]
Babel support added in v2.0 
Node.js V4.3.2 added in v2.1
