### ISSUE TITLE
Clear dist folder before archiving

### ISSUE THREAD

**Issue by s-voloshynenko** [numo-labs/aws-lambda-deploy#28]
I faced with issue, that deploy module doesn't clear ​*dist*​ folder before archiving him. So I got files from previously archived functions.

**Comment by nelsonic** [comment]
adding this to the `dpl.js` now. :+1:

**Comment by s-voloshynenko** [comment]
@nelsonic yes, it will be fine. Maybe in this case before new deployment we should check if `/dist` folder is exist for safe performance and after each deploy clean up after themselves.

**Comment by s-voloshynenko** [comment]
@nelsonic I think that in all cases we should clear this folder - regardless of deploying result (was it uploaded or not). Maybe we should delete\clear this folder before copying files? It will guarantee safety execution.

**Comment by nelsonic** [comment]
Ok. will do the `clean_up()` *before* the `copy_files()` so that its possible to debug in case required. :+1:
