### ISSUE TITLE
Babel es2015 preset seems to be needed in the project folder

### ISSUE THREAD

**Issue by nikhilaravi** [numo-labs/aws-lambda-deploy#29]
I got an error:
`
Couldn't find preset "es2015" relative to directory "/Users/Nikhila/Documents/Coding/TC/lambda-package-search-controller"
`
so I had to add back in the .babelrc and `babel-preset-es2015` even though I am not using any es6 in my code. 

Any ideas why?

**Comment by nelsonic** [comment]
@nikhilaravi what were you trying to run? :confused: 
show me in the morning... :wink:

**Comment by nikhilaravi** [comment]
don't worry! this was a non-issue..

**Comment by nelsonic** [comment]
:+1: thanks for closing it.
