### ISSUE TITLE
Deploy run as part of CI job fails silently

### ISSUE THREAD

**Issue by lennym** [numo-labs/aws-lambda-deploy#49]
If the deployment of a lambda fails for missing `Role` credentials in the environment variables then the process still exits with a zero exit code and CI environments report that the deployment was successful until you view the logs to find errors.

Failed deployments should exit with a non-zero exit code.

**Comment by tomgco** [comment]
:+1: This also exhibits itself when no credentials are supplied.

**Comment by nelsonic** [comment]
@lennym good point. should it throw an error if the credentials aren't set or if deploy errors?
(*how did you see this, deploying locally or from a particular Lambda*?)

**Comment by lennym** [comment]
It was the deployment job for the new filter provider lambda in codeship.
